export const GAME = {
  MATCH_DURATION_SECONDS: 600,      // 10 minutes
  MIN_EXTRACT_TIME_SECONDS: 60,     // 1 minute before can extract
  MAX_PLAYERS: 6,
  ENTRY_FEE_SATS: 1000,
  SAT_SOFT_FLOOR: 10,
  BLEEDOUT_TIME_SECONDS: 30,
  CACHE_OPEN_TIME_SECONDS: 5,
  REVIVE_TIME_SECONDS: 5,
  HOUSE_CUT_COMPETITION: 0.10,
  CLIP_SIZE: 10,
  STARTING_CLIPS: 2,
  TICK_RATE_MS: 100,
}

export const PLAYER = {
  MAX_HEALTH: 100,
  MAX_STAMINA: 100,
  STAMINA_REGEN_RATE: 10,
  STAMINA_SPRINT_COST: 20,
  STAMINA_BAT_COST: 25,
  CLIP_SIZE: 10,
  STARTING_CLIPS: 2,
  SPEED_WALK: 100,
  SPEED_SPRINT: 180,
  INTERACT_RADIUS: 60,
  BAT_RANGE: 40,
  GUN_DAMAGE: 34,
}

export const CACHE_MULTIPLIERS = {
  small: 1,
  medium: 2,
  large: 4,
  jackpot: 16,
}

export const LEVELS: Record<number, { min: number, max: number, title: string }> = {
  1: { min: 0,    max: 99,   title: 'Fresh Meat' },
  2: { min: 100,  max: 249,  title: 'Seen Some Things' },
  3: { min: 250,  max: 499,  title: 'They Fear The Dead Look In My Eyes' },
  4: { min: 500,  max: 999,  title: 'Known In The Streets' },
  5: { min: 1000, max: 9999, title: 'Street King' },
}

export const ACHIEVEMENT_XP: Record<string, number> = {
  i_am_the_one_who_knocks:            25,
  anybody_else:                        35,
  it_feels_kinda_lonely_now:          100,
  going_medieval_on_that_ass:          40,
  kobe:                                40,
  f_it:                                35,
  michelin_star:                       50,
  cant_see_me:                         40,
  this_is_my_fucken_city:             100,
  i_woke_up_like_this:                 75,
  not_so_fast_buddy:                   30,
  dont_mind_if_i_do:                   50,
  no_witnesses:                        75,
  you_come_at_the_king:                60,
  a_mans_gotta_have_a_code:           100,
  bless_your_heart:                    40,
  i_am_the_danger:                     50,
  winter_is_coming:                    50,
  cry_me_a_river:                      35,
  war_crimes:                          60,
  im_rich_bitch:                       50,
  vip_only:                            40,
  early_bird:                          20,
  rubba_band_man:                      75,
  five_finger_discount:                20,
  finders_keepers:                     50,
  last_man_standing:                  100,
  nothing_like_that_first_hit:         25,
  the_invisible_hand:                  50,
  unrealized_gains:                    10,
  price_of_admission:                  10,
  posthumous_contribution:             10,
  still_warm:                          20,
  fashionably_late:                    50,
  who_gonna_stop_me:                   75,
  lover_not_a_fighter:                 75,
  smoke_and_mirrors:                   40,
  i_have_never_felt_more_alive:        75,
  stop_crying_and_walk_it_off:         60,
  close_but_no_cigar:                  10,
  urban_renewal:                       50,
  glutton_for_punishment:              50,
  built_different:                    100,
  i_aint_dead_yet:                     20,
  ride_or_die:                         50,
  son_of_a_bitch:                      40,
  nothing_personal:                    20,
  pre_existing_condition:              20,
  against_my_better_judgment:          40,
  not_on_my_watch:                     60,
  dead_weight:                         20,
  dog_lover:                           30,
  dog_whisperer:                       60,
  diplomatic_relations:                30,
  turf_war:                            50,
  delete_your_account:                 10,
  occupational_hazard:                 20,
  serve_and_protect:                   20,
  you_lost_homie:                      20,
  participation_trophy:                 5,
  fresh_meat:                           5,
  no_ragrets:                          20,
  this_shit_builds_character:          30,
  thoughts_and_prayers:                10,
  the_funeral_was_nice:                20,
  supply_side_economics:               10,
  this_is_fine:                        30,
  started_from_the_bottom:             50,
  now_we_here:                        100,
  now_the_whole_team:                 200,
}
